### PR TITLE
Add zombienet config for rinzler

### PR DESCRIPTION
**Pull request by Rubberbandits**
Add a config which allows zombienet to be used with paratensor. Launches two relay validators and a single parachain collator. Zombienet handles registering parachains and all other initial setup on boot.

Run zombienet with these arguments:
`./zombienet-linux-x64 --provider native spawn scripts/rinzler_zombienet_config.toml`

@eduardogr @unconst

### CODE REVIEW

**Comment by eduardogr** [comment]
Nice @Rubberbandits ! Thanks a lot

What do you think about
- adding some documenntation about how to use this file when using zombienets
- and also introducing why someone would want to use zombienets?

I think this could bring context and enrich the repository for newcomers or people not used to this context (like me :P or other collabs that could be involved in blockchains stuff without having any deep expertise)

**Comment by Rubberbandits** [comment]
> 

Working on this now, do you want me to push to this PR branch or open a new PR?

**Comment by eduardogr** [comment]
> > 
> 
> Working on this now, do you want me to push to this PR branch or open a new PR?

I think it fits in this PR but feel free to do it in the way you consider

I would say that If you want to enable others to use your contribution it's better to merge. If we do not need to share this now, you can keep continue working on this branch/PR

**Comment by Rubberbandits** [comment]
Lets go ahead and merge this now just so we can get people on zombienet ASAP. I'm opening a new PR now with documentation

**Review by eduardogr — APPROVED** [review]
LGTM

**Review by unconst — APPROVED** [review]

**Review by unconst — APPROVED** [review]

**Pull request merged**
